# Generated by Django 5.1.4 on 2025-01-12 09:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Adres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("نام_نام_خانوادگی", models.CharField(max_length=30)),
                ("تلفن", models.CharField(max_length=15)),
                ("شهر", models.CharField(max_length=20)),
                ("ادرس", models.CharField(max_length=255)),
                ("تعداد_واحد", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("نام_نام_خانوادگی", models.CharField(max_length=30)),
                ("تلفن", models.CharField(max_length=15)),
                ("شهر", models.CharField(max_length=20)),
                ("ادرس", models.CharField(max_length=255)),
                ("تعداد_واحد", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("نام_نام_خانوادگی", models.CharField(max_length=30)),
                ("تلفن", models.CharField(max_length=11)),
                ("پیام", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="UserInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("عنوان", models.CharField(max_length=100)),
                (
                    "نوع_ساختمان",
                    models.CharField(
                        choices=[
                            ("مسکونی", "مسکونی"),
                            ("اداری", "اداری"),
                            ("سایر", "سایر"),
                        ],
                        max_length=100,
                    ),
                ),
                ("شهر", models.CharField(max_length=100)),
                ("آدرس", models.CharField(max_length=255)),
                ("موجودی_اولیه", models.PositiveIntegerField(default=0)),
                ("تاریخ", models.DateField()),
                (
                    "شبا",
                    models.CharField(
                        default="",
                        max_length=24,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="فقط اعداد مجاز هستند", regex="^\\d+$"
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("مبلغ", models.PositiveIntegerField()),
                ("تاریخ", models.DateField()),
                ("پرداخت_شده", models.BooleanField(default=False)),
                (
                    "واحد",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.adres"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("نوع_ساختمان", models.CharField(max_length=100)),
                ("واحد", models.CharField(max_length=10)),
                ("رمز_مشترک", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("نوع_ساختمان", models.CharField(max_length=100)),
                ("واحد", models.CharField(max_length=10)),
                ("رمز_مشترک", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
