# Generated by Django 5.1.4 on 2025-01-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_invitation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invitation",
        ),
    ]
